import { of } from 'rxjs';

export class MockAcnhService {
    getVillagers() {
        return of([
            {
                "id":1,
                "fileName":"ant00",
                "name":{
                   "name-USen":"Cyrano",
                   "name-EUen":"Cyrano",
                   "name-EUde":"Theo",
                   "name-EUes":"Cirano",
                   "name-USes":"Cirano",
                   "name-EUfr":"Cyrano",
                   "name-USfr":"Cyrano",
                   "name-EUit":"Cirano",
                   "name-EUnl":"Cyrano",
                   "name-CNzh":"阳明",
                   "name-TWzh":"陽明",
                   "name-JPja":"さくらじま",
                   "name-KRko":"사지마",
                   "name-EUru":"Сирано"
                },
                "personality":"Cranky",
                "birthdayString":"March 9th",
                "birthday":"9/3",
                "species":"Anteater",
                "gender":"Male",
                "catchPhrase":"ah-CHOO",
                "iconUri":"https://acnhapi.com/v1/icons/villagers/1",
                "imageUri":"https://acnhapi.com/v1/images/villagers/1",
                "catchTranslations":{
                   "catch-USen":"ah-CHOO",
                   "catch-EUen":"ah-CHOO",
                   "catch-EUde":"schneuf",
                   "catch-EUes":"achús",
                   "catch-USes":"achús",
                   "catch-EUfr":"ATCHOUM",
                   "catch-USfr":"ATCHOUM",
                   "catch-EUit":"ett-CCIÙ",
                   "catch-EUnl":"ha-TSJOE",
                   "catch-CNzh":"有的",
                   "catchTWzh":"有的",
                   "catch-JPja":"でごわす",
                   "catch-KRko":"임돠",
                   "catch-EUru":"апчхи"
                }
             },
             {
                "id":2,
                "fileName":"ant01",
                "name":{
                   "name-USen":"Antonio",
                   "name-EUen":"Antonio",
                   "name-EUde":"Siggi",
                   "name-EUes":"Antonio",
                   "name-USes":"Antonio",
                   "name-EUfr":"Antonio",
                   "name-USfr":"Antonio",
                   "name-EUit":"Antonio",
                   "name-EUnl":"Antonio",
                   "name-CNzh":"阿诚",
                   "name-TWzh":"阿誠",
                   "name-JPja":"マコト",
                   "name-KRko":"퍼머거",
                   "name-EUru":"Антонио"
                },
                "personality":"Jock",
                "birthdayString":"October 20th",
                "birthday":"20/10",
                "species":"Anteater",
                "gender":"Male",
                "catchPhrase":"honk",
                "iconUri":"https://acnhapi.com/v1/icons/villagers/2",
                "imageUri":"https://acnhapi.com/v1/images/villagers/2",
                "catchTranslations":{
                   "catch-USen":"honk",
                   "catch-EUen":"honk",
                   "catch-EUde":"schlürrrf",
                   "catch-EUes":"fufuf",
                   "catch-USes":"fufuf",
                   "catch-EUfr":"pouet",
                   "catch-USfr":"pouet",
                   "catch-EUit":"honk",
                   "catch-EUnl":"snuit",
                   "catch-CNzh":"真诚",
                   "catchTWzh":"真誠",
                   "catch-JPja":"ホントに",
                   "catch-KRko":"진짜로",
                   "catch-EUru":"го-го-го"
                }
             },
             {
                "id":3,
                "fileName":"ant02",
                "name":{
                   "name-USen":"Pango",
                   "name-EUen":"Pango",
                   "name-EUde":"Mathilda",
                   "name-EUes":"Aspidora",
                   "name-USes":"Aspidora",
                   "name-EUfr":"Mathilda",
                   "name-USfr":"Mathilda",
                   "name-EUit":"Carlotta",
                   "name-EUnl":"Pango",
                   "name-CNzh":"佩希",
                   "name-TWzh":"佩希",
                   "name-JPja":"パトラ",
                   "name-KRko":"패트라",
                   "name-EUru":"Панго"
                },
                "personality":"Peppy",
                "birthdayString":"November 9th",
                "birthday":"9/11",
                "species":"Anteater",
                "gender":"Female",
                "catchPhrase":"snooooof",
                "iconUri":"https://acnhapi.com/v1/icons/villagers/3",
                "imageUri":"https://acnhapi.com/v1/images/villagers/3",
                "catchTranslations":{
                   "catch-USen":"snooooof",
                   "catch-EUen":"snooooof",
                   "catch-EUde":"schnieef",
                   "catch-EUes":"snuf-snuf",
                   "catch-USes":"snuf-snuf",
                   "catch-EUfr":"pouuuuuf",
                   "catch-USfr":"pouuuuuf",
                   "catch-EUit":"snuuf",
                   "catch-EUnl":"snufffff",
                   "catch-CNzh":"希希",
                   "catchTWzh":"希希",
                   "catch-JPja":"だっしー",
                   "catch-KRko":"라지요",
                   "catch-EUru":"снуф-снуф"
                }
             }
        ])
    }

    getVillager() {
        return of( {
            "id":1,
            "fileName":"ant00",
            "name":{
               "name-USen":"Cyrano",
               "name-EUen":"Cyrano",
               "name-EUde":"Theo",
               "name-EUes":"Cirano",
               "name-USes":"Cirano",
               "name-EUfr":"Cyrano",
               "name-USfr":"Cyrano",
               "name-EUit":"Cirano",
               "name-EUnl":"Cyrano",
               "name-CNzh":"阳明",
               "name-TWzh":"陽明",
               "name-JPja":"さくらじま",
               "name-KRko":"사지마",
               "name-EUru":"Сирано"
            },
            "personality":"Cranky",
            "birthdayString":"March 9th",
            "birthday":"9/3",
            "species":"Anteater",
            "gender":"Male",
            "catchPhrase":"ah-CHOO",
            "iconUri":"https://acnhapi.com/v1/icons/villagers/1",
            "imageUri":"https://acnhapi.com/v1/images/villagers/1",
            "catchTranslations":{
               "catch-USen":"ah-CHOO",
               "catch-EUen":"ah-CHOO",
               "catch-EUde":"schneuf",
               "catch-EUes":"achús",
               "catch-USes":"achús",
               "catch-EUfr":"ATCHOUM",
               "catch-USfr":"ATCHOUM",
               "catch-EUit":"ett-CCIÙ",
               "catch-EUnl":"ha-TSJOE",
               "catch-CNzh":"有的",
               "catchTWzh":"有的",
               "catch-JPja":"でごわす",
               "catch-KRko":"임돠",
               "catch-EUru":"апчхи"
            }
         })
    }
}